// Bundles every SVG Aerium draws with (design-system assets plus src/icons)
// into src/generated/assets.js, so pages opened straight from disk (file://)
// can draw icons onto canvases without tainting them.
// Run: node tools/build-assets.mjs
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assets = {};

const clean = (svg) => svg.replace(/\s*\n\s*/g, ' ').trim();

for (const group of ['icons', 'imagery', 'textures', 'decorative', 'avatars']) {
  const dir = join(root, 'design-system/assets', group);
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.svg'))) {
    assets[`${group}/${basename(f, '.svg')}`] = clean(readFileSync(join(dir, f), 'utf8'));
  }
}
for (const f of readdirSync(join(root, 'src/icons')).filter((f) => f.endsWith('.svg'))) {
  assets[`icons/${basename(f, '.svg')}`] = clean(readFileSync(join(root, 'src/icons', f), 'utf8'));
}

// Composite icons: a base object with a smaller object resting on it.
function prefixIds(svg, p) {
  return svg.replace(/id="([^"]+)"/g, `id="${p}$1"`).replace(/url\(#([^)]+)\)/g, `url(#${p}$1)`);
}
function inner(svg) {
  return svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
}
function compose(base, overlay, { x = 26, y = 26, size = 34 } = {}) {
  const b = assets[base], o = prefixIds(assets[overlay], 'o_');
  return b.replace(/<\/svg>\s*$/, `<svg x="${x}" y="${y}" width="${size}" height="${size}" viewBox="0 0 64 64">${inner(o)}</svg></svg>`);
}
const composites = {
  'icons/folder-documents': ['icons/folder', 'icons/document', { x: 20, y: 20, size: 32 }],
  'icons/folder-pictures': ['icons/folder', 'icons/photo', { x: 18, y: 22, size: 32 }],
  'icons/folder-music': ['icons/folder', 'icons/music', { x: 19, y: 20, size: 32 }],
  'icons/folder-videos': ['icons/folder', 'icons/video', { x: 18, y: 22, size: 32 }],
  'icons/folder-games': ['icons/folder', 'icons/gamepad', { x: 18, y: 22, size: 32 }],
  'icons/folder-downloads': ['icons/folder', 'icons/download', { x: 20, y: 22, size: 30 }],
  'icons/folder-desktop': ['icons/folder', 'icons/monitor', { x: 18, y: 22, size: 32 }],
  'icons/folder-user': ['icons/folder', 'icons/user', { x: 20, y: 20, size: 32 }],
  'icons/mediaplayer': ['icons/disc', 'icons/play', { x: 30, y: 28, size: 32 }],
  'icons/photogallery': ['icons/photo', 'icons/star', { x: 34, y: 30, size: 28 }],
  'icons/defender': ['icons/shield', 'icons/check', { x: 30, y: 30, size: 30 }],
  'icons/aquarium': ['icons/bubble', 'icons/fish', { x: 12, y: 12, size: 40 }],
  'icons/welcome': ['icons/aerium', 'icons/star', { x: 34, y: 32, size: 28 }],
  'icons/network': ['icons/monitor', 'icons/globe', { x: 30, y: 28, size: 32 }],
  'icons/computer': ['icons/laptop', 'icons/monitor', { x: 0, y: 0, size: 0 }],
};
for (const [name, [b, o, opt]] of Object.entries(composites)) {
  if (opt.size === 0) { assets[name] = assets[b]; continue; }
  assets[name] = compose(b, o, opt);
}

const keys = Object.keys(assets).sort();
let js = '/* Generated by tools/build-assets.mjs. Do not edit by hand. */\n';
js += '(function () {\n  var A = window.Aerium = window.Aerium || {};\n  A.ASSET_SVG = {\n';
js += keys.map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(assets[k])}`).join(',\n');
js += '\n  };\n})();\n';
mkdirSync(join(root, 'src/generated'), { recursive: true });
writeFileSync(join(root, 'src/generated/assets.js'), js);
console.log('assets.js written:', keys.length, 'assets,', (js.length / 1024).toFixed(0), 'KB');
