// Bundles the photographs Aerium draws with (src/photos, described in
// src/photos/photos.json) into src/generated/photos.js as data URLs, so the
// page works straight from disk (file://) and canvases stay untainted.
// Also writes src/photos/CREDITS.md from the credit lines in photos.json.
// Run: node tools/build-photos.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'src/photos');
const list = JSON.parse(readFileSync(join(dir, 'photos.json'), 'utf8'));

// Width and height from a WebP header (lossy, lossless or extended).
function webpSize(b) {
  if (b.toString('ascii', 0, 4) !== 'RIFF' || b.toString('ascii', 8, 12) !== 'WEBP') throw new Error('not a WebP file');
  const kind = b.toString('ascii', 12, 16);
  if (kind === 'VP8X') return [1 + b.readUIntLE(24, 3), 1 + b.readUIntLE(27, 3)];
  if (kind === 'VP8L') {
    const v = b.readUInt32LE(21);
    return [1 + (v & 0x3fff), 1 + ((v >> 14) & 0x3fff)];
  }
  if (kind === 'VP8 ') return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
  throw new Error('unknown WebP chunk ' + kind);
}

const out = {};
let bytes = 0;
for (const [id, p] of Object.entries(list)) {
  const buf = readFileSync(join(dir, p.file));
  const [w, h] = webpSize(buf);
  bytes += buf.length;
  const entry = { src: 'data:image/webp;base64,' + buf.toString('base64'), w, h };
  for (const k of Object.keys(p)) if (k !== 'file' && k !== 'credit') entry[k] = p[k];
  if (p.credit) entry.credit = { title: p.credit.title, author: p.credit.author, license: p.credit.license, source: p.credit.source };
  out[id] = entry;
}

let js = '/* Generated by tools/build-photos.mjs from src/photos. Do not edit by hand. */\n';
js += '(function () {\n  var A = window.Aerium = window.Aerium || {};\n  A.PHOTOS = {\n';
js += Object.keys(out).sort().map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(out[k])}`).join(',\n');
js += '\n  };\n';
// Photos are handed out as blob: URLs (made on first use), like the icons.
js += `  A.photoURL = function (key) {
    var p = A.PHOTOS[key];
    if (!p) return '';
    if (!p.url) {
      try {
        var bin = atob(p.src.slice(p.src.indexOf(',') + 1)), n = bin.length, bytes = new Uint8Array(n);
        for (var i = 0; i < n; i++) bytes[i] = bin.charCodeAt(i);
        p.url = URL.createObjectURL(new Blob([bytes], { type: 'image/webp' }));
      } catch (e) {
        p.url = p.src;
      }
    }
    return p.url;
  };
})();
`;
mkdirSync(join(root, 'src/generated'), { recursive: true });
writeFileSync(join(root, 'src/generated/photos.js'), js);

// Credits: every photo is openly licensed; CC BY and CC BY-SA need a credit.
let md = '# Photo credits\n\n';
md += 'The fish, plants, stones and wood in the aquarium are real photographs, cut out of their\n';
md += 'backgrounds and color-matched to the tank. All of them come from Wikimedia Commons or\n';
md += 'ambientCG under open licenses. Our cut-out versions of the CC BY-SA photos are shared\n';
md += 'under the same license as the original.\n\n';
md += '| Picture | Original | Author | License |\n|---|---|---|---|\n';
for (const [id, p] of Object.entries(list)) {
  const c = p.credit || {};
  md += `| ${p.file} | [${c.title || 'source'}](${c.source || ''}) | ${c.author || 'unknown'} | ${c.license || ''} |\n`;
}
writeFileSync(join(dir, 'CREDITS.md'), md);
console.log('photos.js written:', Object.keys(out).length, 'photos,', (bytes / 1024).toFixed(0), 'KB of images,', (js.length / 1024).toFixed(0), 'KB of script');
