// Generates design-system/tokens.css from design-system/tokens.json.
// Run: node tools/build-tokens.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'design-system/tokens.json'), 'utf8'));
const themes = tokens.color.themes.map((t) => t.id);
const first = themes[0];

const perTheme = Object.fromEntries(themes.map((t) => [t, []]));
const shared = [];

function add(name, value) {
  if (value && typeof value === 'object') {
    for (const t of themes) {
      const v = value[t] ?? value[first];
      perTheme[t].push(`  --${name}: ${v};`);
    }
  } else {
    shared.push(`  --${name}: ${value};`);
  }
}

for (const tok of tokens.color.tokens) add(tok.name, tok.value);
for (const family of Object.keys(tokens)) {
  if (['name', 'version', 'color', 'type'].includes(family)) continue;
  const fam = tokens[family];
  if (!fam || !Array.isArray(fam.tokens)) continue;
  for (const tok of fam.tokens) add(tok.name, tok.value);
}
for (const [key, stack] of Object.entries(tokens.type.families)) shared.push(`  --font-${key}: ${stack};`);

const typeRules = [];
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    const parts = [
      `font-family: var(--font-${group.family})`,
      `font-size: ${s.fontSize}`,
      `line-height: ${s.lineHeight}`,
      `font-weight: ${s.fontWeight}`,
    ];
    if (s.letterSpacing) parts.push(`letter-spacing: ${s.letterSpacing}`);
    if (s.name === 'y2k-tag') parts.push('text-transform: uppercase');
    typeRules.push(`.t-${s.name} { ${parts.join('; ')}; }`);
  }
}

let css = `/* Generated by tools/build-tokens.mjs from tokens.json. Do not edit by hand. */\n`;
css += `/* ${tokens.name} v${tokens.version}: themes ${themes.join(', ')} */\n\n`;
css += `:root {\n${shared.join('\n')}\n}\n\n`;
themes.forEach((t) => {
  const sel = t === first ? `:root, [data-theme="${t}"]` : `[data-theme="${t}"]`;
  css += `${sel} {\n${perTheme[t].join('\n')}\n}\n\n`;
});
css += typeRules.join('\n') + '\n';

writeFileSync(join(root, 'design-system/tokens.css'), css);
console.log('tokens.css written:', themes.length, 'themes,', tokens.color.tokens.length, 'colors');
